baseURL = 'http://localhost:1313/'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

title = 'Chamonix Holiday Apartments'


# Enable multilingual features
enableGitInfo = false
enableRobotsTXT = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1
    [languages.en.permalinks]
      apartments = "/apartments/:filename"

    [languages.en.params]
      footerAboutText = "We’re a local couple living in Chamonix who have been renting our apartments for over 10 years."
    

  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    languageCode = "fr"
    weight = 2
    [languages.fr.permalinks]
      appartements = "/appartements/:filename"
    [languages.fr.params]
      footerAboutText = "Nous sommes un couple local vivant à Chamonix et louons nos appartements depuis plus de 10 ans."

[build]
  writeStats = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"
  
[params]
  description = "Luxury apartments in the heart of Chamonix"
  default_og_image = "static/images/stylish_apartments_in_the_heart_of_chamonix.jpg"