[[main]]
name = "Home"
url = ""
weight = 10


[[main]]
identifier = "apartments"
url = "apartments"
name = "Apartments"
weight = 40

[[main]]
name = "Couvercle 2 bed "
url = "apartments/couvercle"
weight = 100
parent = "apartments"

[[main]]
name = "Charpoua 1 bed"
url = "apartments/charpoua/"
weight = 100
parent = "apartments"

# [[main]]
# name = "Betty 1 bed"
# url = "apartments/betty/"
# weight = 100
# parent = "apartments"

[[main]]
name = "Contact"
url = "contact"
weight = 100
